In [12]:
import numpy as np

# very basic

marks = [85, '90', True, 92, 88]
type(marks)  # list

total = 0
for i in marks:
    total +=i
print(total)


TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [21]:
a = np.array([85, 90, '78', '92', 88,], dtype=np.float64)
type(a)  # numpy.ndarray
a.ndim
a.shape
a.dtype
print(a)

for i in a:
    total += i
print(total)

# conclusion :
# The numpy array is more efficient for numerical operations compared to a list.
# It automatically handles type conversion and provides useful attributes for analysis.
# it stores data in a contiguous block of memory, allowing for faster access and manipulation.

[85. 90. 78. 92. 88.]
3117.0


In [27]:
# next topic
# operation  ??
# add , subtract, multiply, divide
a = np.array([1, 2, 3, 4]) # ndim 1
b = np.array([5, 6, 7, 8]) # ndim 1
c = a % b
c

array([1, 2, 3, 4])

In [ ]:
# 2D data
a = np.array([[1, 2, 3], [4, 5, 6]]) # ndim 2
b = np.array([[7, 8, 9], [10, 11]]) # ndim 2
c = a + b
c

# here you are getting error because size mismatch

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [40]:
# sales of 3 products provided daily sales
import pandas as pd
sales = np.array([[100, 200, 300], [400, 500, 600],[500, 600, 700]]) # ndim 2

# df = pd.DataFrame(sales, columns=["Product A", "Product B", "Product C"])
# df.describe()

sales.mean(axis=0)  # mean sales per product
# axis mean 0 calculates the mean across columns (daily sales), resulting in mean sales for each product
# if you change axis to 1- row-wise mean sales for each day

array([333.33333333, 433.33333333, 533.33333333])

In [41]:
sales

array([[100, 200, 300],
       [400, 500, 600],
       [500, 600, 700]])

In [42]:
df = pd.DataFrame(sales, columns=["Product A", "Product B", "Product C"])
df.describe()

Product A   Product B   Product C
count    3.000000    3.000000    3.000000
mean   333.333333  433.333333  533.333333
std    208.166600  208.166600  208.166600
min    100.000000  200.000000  300.000000
25%    250.000000  350.000000  450.000000
50%    400.000000  500.000000  600.000000
75%    450.000000  550.000000  650.000000
max    500.000000  600.000000  700.000000

In [44]:
# matrix operations
mat_a = np.array([[1, 2], [3, 4]])
print('shape of mat_a:', mat_a.shape)
print(' mat_a:', mat_a)
mat_b = np.array([[5, 6], [7, 8]])
print(' mat_b:', mat_b)
print(' shape of mat_b:', mat_b.shape)
mat_c = mat_a + mat_b
print(' mat_c:', mat_c)

shape of mat_a: (2, 2)
 mat_a: [[1 2]
 [3 4]]
 mat_b: [[5 6]
 [7 8]]
 shape of mat_b: (2, 2)
 mat_c: [[ 6  8]
 [10 12]]


In [74]:
mat_a = np.array([[1, 2], [4, 5]])
print('shape of mat_a:', mat_a.shape)

mat_b = np.array([[2], [3]])
print('shape of mat_b:', mat_b.shape)

# lets try to multiply
mat_d = mat_a * mat_b
print('shape of mat_d:', mat_d.shape)
mat_d

# broadcasting? # link https://numpy.org/doc/stable/user/basics.broadcasting.html
# https://blog.finxter.com/numpy-broadcasting-a-simple-tutorial/

shape of mat_a: (2, 2)
shape of mat_b: (2, 1)
shape of mat_d: (2, 2)


array([[ 2,  4],
       [12, 15]])

In [56]:
np.linspace(0, 10, num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [65]:
a = np.arange(6)
a.ndim
b = a.reshape(3, 3) # here 2 means rows and 3 means columns
b

ValueError: cannot reshape array of size 6 into shape (3,3)

In [68]:
a

array([0, 1, 2, 3, 4, 5])

In [72]:
a[1:3]  # first row, second column

array([1, 2])

In [73]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a > 5]  # all elements greater than 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
# https://numpy.org/doc/stable/user/absolute_beginners.html
# please refer official documentation : Assignment
